### ISSUE TITLE
github.com/fatih/color no longer maintained

### ISSUE THREAD

**Issue by meyermarcel** [meyermarcel/icm#10]
Could this be a new package for color terminal output?

https://github.com/logrusorgru/aurora

**Comment by srlehn** [comment]
I am using https://github.com/mattn/go-colorable this way:

```go
import (
	"fmt"

	"github.com/mattn/go-colorable"
)

var coloredOutput = colorable.NewColorableStdout()

func Printf(format string, a ...interface{}) (int, error) {
	return fmt.Fprintf(coloredOutput, format, a...)
}
```

ANSI color escape codes will then be interpreted by go-colorable for Windows.

**Comment by meyermarcel** [comment]
I would to keep the question of finding a more recent package than github.com/fatih/color. So I added a new issue for [color support in windows](https://github.com/meyermarcel/icm/issues/12)
