### ISSUE TITLE
Expose /internal functions

### ISSUE THREAD

**Issue by srlehn** [meyermarcel/icm#11]
Is it possible to expose some of the functionality in /internal so that other go projects can make use of it by importing?

**Comment by meyermarcel** [comment]
Thanks for your comment. If someone needs the functions of the internal package, sure I would expose them or create a library.

**Comment by meyermarcel** [comment]
@srlehn Is the commit 3836b73e2a201ac8ab906ab9c1ad09c8e0f89541 solving this issue?
