### ISSUE TITLE
Color support in Windows

### ISSUE THREAD

**Issue by meyermarcel** [meyermarcel/icm#12]
I am using https://github.com/mattn/go-colorable this way:

```go
import (
	"fmt"

	"github.com/mattn/go-colorable"
)

var coloredOutput = colorable.NewColorableStdout()

func Printf(format string, a ...interface{}) (int, error) {
	return fmt.Fprintf(coloredOutput, format, a...)
}
```

ANSI color escape codes will then be interpreted by go-colorable for Windows.

_Originally posted by @srlehn in https://github.com/meyermarcel/icm/issues/10#issuecomment-616477780_

**Comment by meyermarcel** [comment]
Does this commit 6709ff5750b8f1e1797843aef9846c9eec31536d allow correct color in Windows?

**Comment by srlehn** [comment]
You shouldn't use both github.com/fatih/color and github.com/mattn/go-colorable.

go-colorable already makes it possible to generate color output for different OS in a uniform way. It requires to set the colors via ANSI escape codes similar to this:

![image](https://user-images.githubusercontent.com/48837958/79785629-727c8780-8344-11ea-849b-055bd3a0e5f7.png)

github.com/fatih/color on the other hand lets you set the colors with color.FgGreen, etc.
github.com/fatih/color is only a small wrapper around github.com/mattn/go-colorable! So don't use both in combination.

It is mostly an easier way to setup go-colorable and doesn't contain much more than the historic ANSI escape codes (which won't change). It being not maintained doesn't matter much for such a case.
The underlying github.com/mattn/go-colorable with the system calls, etc is well maintained.
I would revert the last commit 6709ff5 and keep github.com/fatih/color vendored.

**Comment by meyermarcel** [comment]
Thanks @srlehn for your detailed comment.
I removed the last commit from history and will commit and follow your idea when I have more time and I feel sure that I 100% understood the interaction between github.com/fatih/color and github.com/mattn/go-colorable. Thanks a lot :)

**Comment by meyermarcel** [comment]
Hello @srlehn 
`github.com/fatih/color` was replaced by `github.com/logrusorgru/aurora/v3`. Now there should not be an indirect and direct dependency. What do you think? See d9f10f20fd1df7a16647ca49f603ff95455a982d
