### ISSUE TITLE
Old ISO 6346 standart used

### ISSUE THREAD

**Issue by snussik** [meyermarcel/icm#16]
It seems, that json configs contain old data from ISO6346:1995 (am. 1 2017). 2020 revision has significant changes in container type marking.

**Comment by snussik** [comment]
> > It seems, that json configs contain old data from ISO6346:1995 (am. 1 2017). 2020 revision has significant changes in container type marking.
> 
> Thanks for open this issue :) Could you pinpoint me to a good source of the ISO6346:2020 revision? And do you know which types are missing in https://github.com/meyermarcel/icm/blob/main/data/file/type.json?

I don't have actual revision too. By the way, its actual revision is 2022, now ))
But I've noticed that tanks have "k" letter now: https://www.bic-code.org/type-code-designation/

If I find actual version I'll try to make a revision and pr.

**Comment by meyermarcel** [comment]
> > > It seems, that json configs contain old data from ISO6346:1995 (am. 1 2017). 2020 revision has significant changes in container type marking.
> > 
> > 
> > Thanks for open this issue :) Could you pinpoint me to a good source of the ISO6346:2020 revision? And do you know which types are missing in https://github.com/meyermarcel/icm/blob/main/data/file/type.json?
> 
> I don't have actual revision too. By the way, its actual revision is 2022, now )) But I've noticed that tanks have "k" letter: https://www.bic-code.org/type-code-designation/

Thanks for the link!

> 
> If I find actual version I'll try to make a revision and pr.

I had some time and created a PR: https://github.com/meyermarcel/icm/pull/17

**Comment by meyermarcel** [comment]
@snussik 👋
